# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Pi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Pi
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'iosMath'
  pod 'JVFloatLabeledTextField'
  pod 'Canvas'
  pod 'FXBlurView', '~> 1.6.4'
end

target 'Pi watchOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pi watchOS

end

target 'Pi watchOS Extension' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pi watchOS Extension

end
